export const GETPRODUCT= 'GETPRODUCT';
export const POSTPRODUCT = "POSTPRODUCT";
export const EDITPRODUCT = 'EDITPRODUCT'
export const DELETPRODUCT ='DELETPRODUCT'
export const GETONEPRODUCT='GETONEPRODUCT'